#!/bin/bash

mkdir ~/bin -p

cp bin/* ~/bin

mkdir ~/env -p

APPDIR=`ls -d ~`
echo $APPDIR > ~/env/APPDIR

echo "$APPDIR/app" > ~/env/CURATOR_REPO_DIR

if [ ! -f ~/env/CURATOR_LISTEN_PORT ]; then
	echo $(expr $UID + 50000) > ~/env/CURATOR_LISTEN_PORT
fi
